# Generated by Django 6.0.3 on 2026-03-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("ALCOHOL", "Alcohol Detected"),
                            ("DROWSINESS", "Driver Drowsy"),
                            ("OVERLOAD", "Vehicle Overloaded"),
                            ("TEMPERATURE", "High Temperature"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        help_text="Full sensor readings at the time of incident"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
    ]
