# Generated by Django 6.0.3 on 2026-03-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_violation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="violation",
            name="vehicle",
        ),
        migrations.AddField(
            model_name="violation",
            name="device_id",
            field=models.CharField(
                default=1, help_text="ESP32 ID from Firebase", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="violation",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="violations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
